README.md, docs/how-to-review-new-components.md, now-build.sh, now.json
In order to ease reviewing when adding new components to Storybook, let's use **Zeit** in order to **automatically deploy each PR** on an isolated environment.
* introduce Zeit `now`
=> Introduce Zeit (now) auto deploy

packages/css/src/components/Button.css
This is needed because using a `border` property makes the button larger than expected (40px vs 38px)
=> Use box-shadow instead of border for Buttons

packages/react/src/components/index.js
The Selector and SelectorField were not being exported through the React's `index.js` and not available in the final build.
=> Export Selector and SelectorField to be available in the final build

package.json, packages/css/package.json, packages/react/package.json
Set node v12.14.0 as the minimal required version, but also allow greater ones (13.x at the moment)
=> Fix engines in package.json

packages/react/src/components/FileUploader/index.js, packages/react/src/components/FileUploader/index.stories.js, packages/react/src/components/ImageUploader/index.js, packages/react/src/components/ImageUploader/index.stories.js, packages/react/src/components/UploaderImageItem/index.js, packages/react/src/components/UploaderItem/index.js
Allow passing a default `value` props for each type of uploaders
The value must be an `Array` of file-like items
For `FileUploader`, a back-end could send a file-like structure via JSON 
```
const stubFile1 = {
name: 'stub-file-1.txt',
type: 'text',
};
```
Same for an `ImageUploader`, while including the file URL into a `preview` entry
```
const stubFile1 = {
name: 'image-stub-1',
type: 'image/jpg',
preview: 'https://api.adorable.io/avatars/285/10@adorable.io.png',
};
```
Bonus: it will fix https://github.com/heetch/flamingo/issues/76
=> Accept uploads default value

packages/react/src/components/SidePanel/index.js, packages/react/src/components/SidePanel/index.stories.js
- Add a `header` prop to SidePanel, to use Components in it
For a new feature in the admin, we need to be able to send React components to the `side panel` header the way we do it for the footer.
=> Add a `header` prop to SidePanel, to use Components in it

packages/react/src/components/SidePanel/index.js
I had added an empty div containing the header but removed it. I need to add it back, because the header has styles with `justify-content: space-inbetween`, which makes any component inside of it have a lot of space and not behave like you'd expect it.
=> Add back the div containing the header

packages/react/src/components/Table/index.js, packages/react/src/components/Table/index.stories.js
This PR adds two props to the `Table` component to allow the sorting to be done externally (like on the backend)
- `manualSorting` - to disable the client-side sorting that react-table does, but still keep the state/styling 
- `onChangeSort` - a function which receives the sorted state e.g. `{ desc: false, id: "name" }`
=> Enable manual sorting for table

packages/react/src/components/Table/index.js, packages/react/src/components/Table/index.stories.js
This PR updates the `<Table>` component to support passing the initialState prop to define the default sorting on columns.
=> Allow initial state to be passed to Table

packages/react/rollup.config.js
This change prevents `import 'react-day-picker/lib/style.css'` from being transformed to CSS modules by postcss. This fixes the display of the `Datepicker` component when it's used externally. 
I compared a diff of the dist/index.js and dist/index.es.js files before and after this change, and the only difference is that the styles of the datepicker don't have scoped selectors anymore.
=> Update rollup config for react-day-picker

package.json, rollup.config.js, yarn.lock
During the build phase, the `rollup-plugin-visualizer` package will output a `stats.html` file into the dist folder.
=> Add a task to analyze dist bundle

src/components/ImageUploader/index.js, src/components/ImageUploader/index.stories.js
Some mobile devices don't support the `accept` prop on inputs, leading to app breaking because people tried to upload 2GB videos instead of a photo
=> Stronger image uploader validation

now.json
```
Deployment failed with the following error:
Deploying Serverless Functions to multiple regions is restricted to the Enterprise plan for Teams.
```
Indeed, [Hobby plan](https://vercel.com/docs/configuration#project/regions) doesn't have it anymore.
=> Remove Vercel regions as not part of Hobby plan

src/components/Dropdown/index.js, src/components/InputField/index.js, src/components/SelectField/index.js, src/components/SelectorField/index.js, src/components/TextareaField/index.js, src/components/UploaderField/index.js, src/components/_DeprecatedFileUploaderField/index.js, src/components/_DeprecatedImageUploaderField/index.js
By adding a small check for proptypes that refer to `HTMLElement` or `Element` these components would be safe to use with SSR
=> Make component propTypes SSR friendly

src/components/Datepicker/index.js
Right now we can pass a String but we get a proptype error in console
=> Allow string or Date for Datepicker

src/components/Table/index.js, src/components/Table/index.stories.js, src/components/Textarea/index.stories.js
This PR adds the prop `onClickRow` to the `Table` component. When a row is clicked, the original data values will be passed to the handler. E.g.
```javascript
const data = [
{ name: 'Tam', active: true },
{ name: 'Paco', active: false },
];
return (
<Table
data={data}
columns={[
{
Header: 'Name',
accessor: 'name',
},
{
Header: 'Name',
accessor: 'name',
},
]}
onClickRow={row => console.log(row)} //outputs { name: X, active: X }
/>
);
```
=> Allow onClick event for table rows

src/components/Table/index.js
This PR updates the prop type definitions for the Table component to remove the error messages when we have a valid definition of `accessor` as a function
=> Update Table proptypes for accessor

package.json, yarn.lock
This PR fixes the vulnerability identified by dependabot
=> chore: force handlebars resolution to at least 4.7.7

package.json, src/components/Dropdown/index.js, src/components/Popover/index.js, src/components/Popover/index.stories.js, yarn.lock
This PR update Popper to its last version, and add more props to our Popper component to be more flexible.
=> update react-popper to 2.2.5

src/components/Tabs/index.js, src/components/Tabs/index.stories.js
When using objects as elements for `<Tabs />`, React was displaying an error because the component used the object itself as a key. This PR adds a `buildKey` function prop to allow the caller to specify how to build a key for each element.
=> Add custom key feature to Tabs

src/components/Toggle/index.js, src/components/Toggle/index.stories.js
This PR changes the `Toggle` component so it is stateless. This allows to control its state from outside, by updating the `checked` prop; which was not possible before. 
This implies the caller has the responsibility to hold the state.
=> Make Toggle stateless

src/components/Select/index.js, src/components/Toggle/index.js, src/components/Toggle/styles.js, src/styles.css
Aligned text style of the label with other fields. 
Before:
After:
Improved styling and behaviour of the blank option/placeholder.
Before:
After:
There is always an empty option, and it is selected if no `defaultValue` is provided. But if no placeholder text is provided for this empty option, the option itself doesn't appear in the list. 
If a placeholder is provided, it is properly styled, and the option in the list is not selectable once another value has been selected.
Set the default placeholder text color to an actual color of the palette instead of the browser's default.
=> Improve styling

src/components/Uploader/index.js, src/components/Uploader/index.stories.js, src/components/Uploader/styles.js
Linked to [DAB-1169] & Pierre Lange's comment. 
Having the `IconButton` with an unset color on the Uploader is not good UX. 
We don't know that we have to go to the top right of the image uploaded, to actually see the icon, and delete the file. 
I've changed the color, to make it always visible when the file is uploaded. 
UPDATE : I've put the default color in RED (After Pierre's discussions)  - to be aligned between passenger / driver colors  + IconColor can be chosen :) 
[DAB-1169]: https://retool.atlassian.net/browse/DAB-1169?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Uploader - Icon always visible

src/components/SidePanel/index.js
This PR fixes a bad behaviour of SidePanel, especially when we use several of them and different values of a state to determine which one is opened: the component called its onClose function each time isOpen was evaluated to false, even if it had not changed. 
Before:
https://user-images.githubusercontent.com/512823/202407732-9aaa1e98-112f-470a-a38b-e8864e869520.mov
After:
https://user-images.githubusercontent.com/512823/202407784-24adb493-41d8-4a94-8db7-9a9a531d0278.mov
=> fix: SidePanel calling onClose even when already closed

src/components/SidePanel/index.js
The previous fix broke the side panel rendering when the `isOpen` value is changed from the outside when the panel is visible (for exemple from the click on a button inside the panel's children). 
This video shows the panel working correctly in this situation using this fix:
https://user-images.githubusercontent.com/512823/202458028-038cde3f-12f1-415b-8d0c-b0b9748952bc.mov
=> fix: SidePanel not reacting to external change of isOpen
