- packages/css/src/components/Form-el.css
- packages/css/src/components/Input.css
- packages/css/src/components/ListItem.css
- packages/css/src/components/Select.css
- packages/css/src/components/Textarea.css
- packages/css/src/index.css
- packages/react/src/components/Input/README.md
- packages/react/src/components/Input/index.js
- packages/react/src/components/Input/index.stories.js
- packages/react/src/components/Select/index.js
- packages/react/src/components/Select/index.stories.js
- packages/react/src/components/Text/index.stories.js
- packages/react/src/components/Textarea/README.md
- packages/react/src/components/Textarea/index.js
- packages/react/src/components/Textarea/index.stories.js
Update form elements according to the latest specs and QA feedback
- Input
- Select
- Textarea
> Form els/update

- now-build.sh
- package.json
> Add a setup script

- packages/react/src/components/Select/index.js
- packages/react/src/components/Select/index.stories.js
Modified Select component to accept number or string values.
Added example to Storybook
> Select accept number or string values

- packages/css/src/components/Text.css
> Fix Text color

- packages/react/src/components/Input/index.js
- packages/react/src/components/Input/index.stories.js
This is per design https://www.figma.com/file/YOIkND79so4MHXbSt43kBzPY/New-Login-Method?node-id=323%3A713
when a lock icon is required to be presented on password input
> Added possibility to show an icon on Input right handside

- packages/css/src/components/Selector.css
- packages/react/src/components/Selector/index.js
- packages/react/src/components/Selector/index.stories.js
- packages/react/src/components/SelectorField/index.stories.js
The Selector component didn't have `valid` and `invalid` states but I need them for HMTD
> Update Selector component with "valid" and "invalid" states

- packages/react/src/components/SelectField/index.js
> Fix Select import in SelectField component

- packages/css/src/components/Dropdown.css
- packages/css/src/index.css
- packages/react/src/components/Dropdown/index.js
- packages/react/src/components/Dropdown/index.stories.js
This component is inspired by the Popover one
Everything is rendered via render props because we might need to use the `show/hide/toggle` functions
It's recommended to use `Item` as an option, but in the end, you can use whatever you want!
> Create Dropdown component

- packages/react/src/components/index.js
> Fix Dropdown component export

- packages/css/src/components/FileUploader.css
- packages/css/src/components/ImageUploader.css
- packages/react/src/components/FileUploader/index.js
- packages/react/src/components/FileUploader/index.stories.js
- packages/react/src/components/ImageUploader/index.js
- packages/react/src/components/ImageUploader/index.stories.js
Fix a couple of issues leading to weird states and visual glitches
> Image uploader/fix file detection

- packages/css/src/shared/vars.css
Not sure if the name makes sense but we use it quite a lot in the admin and would be nice to have it as a var.
> In Figma the designers have a "concrete" flamingo color.

- packages/react/src/components/Dropdown/index.js
- packages/react/src/components/Dropdown/index.stories.js
Update the Dropdown component to add a new prop `modifiers` that is passed to the `Popper` component. See: https://popper.js.org/docs/v1/#modifiers
> Add support for dropdown modifiers

- packages/css/src/components/Datepicker.css
- packages/css/src/index.css
- packages/react/package.json
- packages/react/src/components/Datepicker/index.js
- packages/react/src/components/Datepicker/index.stories.js
- packages/react/src/components/DatepickerInput/index.js
- packages/react/src/components/DatepickerNavigation/index.js
- packages/react/src/components/index.js
- packages/react/yarn.lock
This PR adds a new datepicker component based on react-day-picker (https://bundlephobia.com/result?p=react-day-picker@7.4.8)
> Datepicker component

- src/components/Card/index.js
- src/components/Datepicker/index.stories.js
- src/components/Dropdown/index.stories.js
- src/components/IconButton/index.stories.js
- src/components/Selector/index.stories.js
- src/components/SelectorField/index.stories.js
- src/components/SidePanel/index.js
- src/components/SidePanel/styles.js
- src/components/Table/index.stories.js
- yarn.lock
- Uniformize stories
- Update `yarn.lock`
- Fix `Card` shadows
> Styled components/uniformize stories 2

- .storybook/preview.js
- .storybook/theme/ThemeProvider.js
- package.json
- yarn.lock
Nothing crazy here
- Install `chakra-ui` and its dependencies
- Add the theme foundations (will evolve alongside new components)
NB: At the moment the theme and the provider are located into the storybook folder, it's temporary and will be moved later on
> Init chakra-ui, add the theme foundations

- src/components/Tabs/index.js
- src/components/Tabs/index.stories.js
This defaultIndex allows us to define which tab should be open on initial render.
> Add defaultIndex to Tabs

- src/components/Uploader/index.js
A little `onChange` escaped from the `onClear` function, _petit malin_
> Call onChange when clearing files

- src/components/Uploader/index.js
- src/components/UploaderField/index.js
- Fix UploaderField component name
- Enforce array conversion of native FileList since most API doesn't support it
> Uploaders fixes

- src/components/Toggle/index.js
The Toggle was a default button which makes it type `submit`, it was submitting forms on every change. It doesn't seem to be a popular component cuz no one noticed 😂
> Make the toggle button type as button"

- src/components/Select/index.js
- src/components/Select/index.stories.js
- src/components/Tabs/index.js
- src/styles.css
Update error, success colours. 
Add new `ok` status colour.
Select component - add optional placeholder
Tabs component - add button type
> Update error, success colors. Update Select, Tabs

- src/components/Toast/index.js
- src/components/Toast/index.stories.js
- src/components/Toast/styles.js
New component Toast added to flamingo.
> Add Toast Component

- src/components/DatepickerDay/index.js
- src/components/DatepickerDay/index.stories.js
- src/components/DatepickerDay/styles.js
- src/components/Toast/index.js
- src/components/Toast/index.stories.js
- src/components/Toast/styles.js
- disable cursor: pointer on whole datepicker fixed
- style disable days, remove hover state on disable days fixed
- Clear button fixed
- year/month drop down is broken fixed
> DatePickerDay fixed

- src/components/Toast/index.js
- src/components/Toast/index.stories.js
- src/components/Toast/styles.js
- src/components/index.js
- Zindex added 
- position fixs
- export added
> Toast Component ajdustements

- src/components/Badge/index.js
- src/components/Badge/index.stories.js
- src/components/Badge/styles.js
This PR add our Badge in the flamingo library
> [TCC-1410] [FE] Add Badge component to Flamingo

- README.md
- src/components/Badge/index.stories.js
- src/components/index.js
This PR add an other example in our Badge story
It also add Badge in our index.js to export it (I forgot to do it in my last PR)
Update README.md on how to create new component
> TCC // export Badge

- .storybook/main.js
- package.json
- yarn.lock
- bump-postcss
- globbing-fix https://github.com/storybookjs/storybook/issues/14342
> bump-postcss/globbing-fix

- src/components/Section/index.js
- src/components/Section/index.stories.js
> feat: make Section expandable

- README.md
- src/components/Tabs/styles.js
Readme update on publishing new versions
Small syntax fix
> Readme update, syntax fix
